### ISSUE TITLE
Type hint allowed values in CPF

### ISSUE THREAD

**Issue by glassjoseph** [snac-cooperative/snac-openrefine-extension#3]
On the Constellation schema page, the CPF fields should have descriptive tooltips. Fields that require constrained values should give the allowed values. 

The tooltips can be defined in `schema-alignment-dialog.js`

Example: 

`EntityType: (person, family, corporateBody)`

**Comment by deternitydx** [comment]
#10 is a duplicate, but has more information.  Closing this issue.
