### ISSUE TITLE
Add support for Source (Citation)

### ISSUE THREAD

**Issue by glassjoseph** [snac-cooperative/snac-openrefine-extension#4]

**Comment by glassjoseph** [comment]
These should be constellation-level sources. Mapping the Citation, Citation-URL, Citation-FoundData to the SNAC Source.

**Comment by deternitydx** [comment]
See the examples in https://github.com/snac-cooperative/data-samples/blob/master/ReferenceExamples/LoC/LoCTables/CPF-Table.tsv

**Comment by deternitydx** [comment]
Unrelated comment from the prior TSV file: one column in TSV contains multiple columns and rows in OpenRefine.  For example, see Dates, which has columns split by ^ and rows are split by #.  Can we do this automatically without asking the user to do this manually after pulling in the data?

**Comment by deternitydx** [comment]
Available in v1.0.0-beta6
