### ISSUE TITLE
Enable easy pulling of SNAC IDs from reconciled values

### ISSUE THREAD

**Issue by glassjoseph** [snac-cooperative/snac-openrefine-extension#7]
To get SNAC IDs from reconciled values, users currently have to click the reconciled column, select "Add column based on this column" and enter `cell.recon.match.id` or `cell.recon.best.id` into the GREL expression box. 

If possible, we should create a button or column menu option "Get SNAC IDs from reconciled values" to perform the above operation in one click.

**Comment by deternitydx** [comment]
This has been added to OpenRefine by default.  See https://github.com/OpenRefine/OpenRefine/issues/1975.

**Comment by deternitydx** [comment]
![Screenshot from 2021-06-30 15-36-11](https://user-images.githubusercontent.com/1839197/124021152-35386e80-d9b9-11eb-9ff2-11379f6307d7.png)

![Screenshot from 2021-06-30 15-36-40](https://user-images.githubusercontent.com/1839197/124021182-3f5a6d00-d9b9-11eb-91c8-5367cba2eb0a.png)
